// GENERATED CODE - DO NOT MODIFY BY HAND
// *******************************************************
// This file was generated by icon_assets_builder.dart
// *******************************************************

import 'package:flutter/widgets.dart';
import 'package:cloudless/presentation/assets/icons.gen.dart' as icons;

class IconAssets {}
