// ignore_for_file: depend_on_referenced_packages

import 'dart:async';

import 'package:build/build.dart';

class IconAssetsBuilder implements Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': ['presentation/assets/icons.g.dart'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = AssetId(
      buildStep.inputId.package,
      'lib/presentation/assets/icons.gen.dart',
    );
    if (!await buildStep.canRead(inputId)) {
      log.warning('File lib/presentation/assets/icons.gen.dart not found.');
      return;
    }

    final iconClass = await buildStep.readAsString(inputId);

    final iconLines = iconClass
        .split('\n')
        .where((line) => line.contains('static const IconData'))
        .toList();

    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// *******************************************************')
      ..writeln('// This file was generated by icon_assets_builder.dart')
      ..writeln('// *******************************************************\n')
      ..writeln("import 'package:flutter/widgets.dart';")
      ..writeln(
        "import 'package:cloudless/presentation/assets/icons.gen.dart' as icons;\n",
      ) // Relative import
      ..writeln('class IconAssets {');

    for (final line in iconLines) {
      final match = RegExp(r'static const IconData (\w+)').firstMatch(line);
      if (match != null) {
        final iconName = match.group(1);
        buffer.writeln('  IconData get $iconName => icons.Icons.$iconName;');
      }
    }

    buffer.writeln('}');

    final outputId = AssetId(
      buildStep.inputId.package,
      'lib/presentation/assets/icons.g.dart',
    );

    try {
      await buildStep.writeAsString(outputId, buffer.toString());
    } catch (e) {
      log.warning('Error $e');
    }
  }
}

Builder iconAssetsBuilder(BuilderOptions options) => IconAssetsBuilder();
