part of '../call_to_action.dart';

extension CTAModeToTheme on CallToActionMode {
  CallToAction withTheme({
    required VoidCallback? action,
    required Widget label,
    required CallToActionTheme theme,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) => CallToAction(
    theme: theme,
    mode: this,
    action: action,
    label: label,
    onLongPress: onLongPress,
    height: height,
    icon: icon,
    iconOnTheRight: iconOnTheRight,
    secondaryIcon: secondaryIcon,
    spaced: spaced,
    horizontalMargin: horizontalMargin,
    borderRadius: borderRadius,
    curve: curve,
    duration: duration,
    key: key,
  );

  CallToAction primary({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) => CallToAction(
    theme: const PrimaryCallToActionTheme(),
    mode: this,
    action: action,
    label: label,
    onLongPress: onLongPress,
    height: height,
    icon: icon,
    iconOnTheRight: iconOnTheRight,
    secondaryIcon: secondaryIcon,
    spaced: spaced,
    horizontalMargin: horizontalMargin,
    borderRadius: borderRadius,
    curve: curve,
    duration: duration,
    key: key,
  );

  CallToAction regular({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) => CallToAction(
    theme: const RegularCallToActionTheme(),
    mode: this,
    action: action,
    label: label,
    onLongPress: onLongPress,
    height: height,
    icon: icon,
    iconOnTheRight: iconOnTheRight,
    secondaryIcon: secondaryIcon,
    spaced: spaced,
    horizontalMargin: horizontalMargin,
    borderRadius: borderRadius,
    curve: curve,
    duration: duration,
    key: key,
  );

  CallToAction secondary({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) => CallToAction(
    theme: const SecondaryCallToActionTheme(),
    mode: this,
    action: action,
    label: label,
    onLongPress: onLongPress,
    height: height,
    icon: icon,
    iconOnTheRight: iconOnTheRight,
    secondaryIcon: secondaryIcon,
    spaced: spaced,
    horizontalMargin: horizontalMargin,
    borderRadius: borderRadius,
    curve: curve,
    duration: duration,
    key: key,
  );

  CallToAction tertiary({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) => CallToAction(
    theme: const TertiaryCallToActionTheme(),
    mode: this,
    action: action,
    label: label,
    onLongPress: onLongPress,
    height: height,
    icon: icon,
    iconOnTheRight: iconOnTheRight,
    secondaryIcon: secondaryIcon,
    spaced: spaced,
    horizontalMargin: horizontalMargin,
    borderRadius: borderRadius,
    curve: curve,
    duration: duration,
    key: key,
  );

  CallToAction danger({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) => CallToAction(
    theme: const DangerCallToActionTheme(),
    mode: this,
    action: action,
    label: label,
    onLongPress: onLongPress,
    height: height,
    icon: icon,
    iconOnTheRight: iconOnTheRight,
    secondaryIcon: secondaryIcon,
    spaced: spaced,
    horizontalMargin: horizontalMargin,
    borderRadius: borderRadius,
    curve: curve,
    duration: duration,
    key: key,
  );
}
