part of '../call_to_action.dart';

extension CTAThemeToMode on CallToActionTheme {
  CallToAction withMode({
    required VoidCallback? action,
    required Widget label,
    required CallToActionMode mode,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) =>
      CallToAction(
        mode: mode,
        theme: this,
        action: action,
        label: label,
        onLongPress: onLongPress,
        height: height,
        icon: icon,
        iconOnTheRight: iconOnTheRight,
        secondaryIcon: secondaryIcon,
        spaced: spaced,
        horizontalMargin: horizontalMargin,
        borderRadius: borderRadius,
        curve: curve,
        duration: duration,
        key: key,
      );

  CallToAction filled({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) =>
      CallToAction(
        mode: CallToActionMode.filled,
        theme: this,
        action: action,
        label: label,
        onLongPress: onLongPress,
        height: height,
        icon: icon,
        iconOnTheRight: iconOnTheRight,
        secondaryIcon: secondaryIcon,
        spaced: spaced,
        horizontalMargin: horizontalMargin,
        borderRadius: borderRadius,
        curve: curve,
        duration: duration,
        key: key,
      );
  CallToAction empty({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) =>
      CallToAction(
        mode: CallToActionMode.empty,
        theme: this,
        action: action,
        label: label,
        onLongPress: onLongPress,
        height: height,
        icon: icon,
        iconOnTheRight: iconOnTheRight,
        secondaryIcon: secondaryIcon,
        spaced: spaced,
        horizontalMargin: horizontalMargin,
        borderRadius: borderRadius,
        curve: curve,
        duration: duration,
        key: key,
      );
  CallToAction outlined({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) =>
      CallToAction(
        mode: CallToActionMode.outlined,
        theme: this,
        action: action,
        label: label,
        onLongPress: onLongPress,
        height: height,
        icon: icon,
        iconOnTheRight: iconOnTheRight,
        secondaryIcon: secondaryIcon,
        spaced: spaced,
        horizontalMargin: horizontalMargin,
        borderRadius: borderRadius,
        curve: curve,
        duration: duration,
        key: key,
      );
  CallToAction filledOutlined({
    required VoidCallback? action,
    required Widget label,
    VoidCallback? onLongPress,
    Widget? icon,
    Widget? secondaryIcon,
    bool? iconOnTheRight,
    bool? spaced,
    double? height,
    double? horizontalMargin,
    BorderRadius? borderRadius,
    Curve? curve,
    Duration? duration,
    Key? key,
  }) =>
      CallToAction(
        mode: CallToActionMode.filledOutlined,
        theme: this,
        action: action,
        label: label,
        onLongPress: onLongPress,
        height: height,
        icon: icon,
        iconOnTheRight: iconOnTheRight,
        secondaryIcon: secondaryIcon,
        spaced: spaced,
        horizontalMargin: horizontalMargin,
        borderRadius: borderRadius,
        curve: curve,
        duration: duration,
        key: key,
      );
}
